### ISSUE TITLE
Licensing discussion

### ISSUE THREAD

**Issue by athy9193** [UBC-MDS/rhousehunter#20]
* To set up issue for discussion on Licensing
*  Lead discussion

**Comment by JuntingHe** [comment]
> * To set up issue for discussion on Licensing
> * Lead discussion

Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly dicussed.

- Examine the MIT license we are currently using
- Decide whether we change the license and why
- Link this issue to the licensing issue in Python

**Comment by JuntingHe** [comment]
Hey folks, after checking the https://choosealicense.com/, I think the following license may be some suitable options for our package. 

- MIT license: short and simple permissive, requiring preservation of copyright and license notices     
     - Permission: commercial use, distribution, modification,  private use
     - Conditions: license and copyright notice, disclose source, same license, state changes

- Boost Software License: simple permissive, requiring preservation of copyright and license notices     
     - Permission: commercial use, distribution, modification,  private use
     - Conditions: license and copyright notice, disclose source, same license, state changes

- GNU GPLv3：strong copyleft, using a licensed work under the same license.
     - Permission: commercial use, distribution, modification,  patent use, private use
     - Conditions: license and copyright notice

- Apache: permissive, requiring preservation of copyright and license notices.
     - Permission: commercial use, distribution, modification,  patent use, private use
     - Conditions: license and copyright notice,  state changes

Personally, I think our original MIT license is the best choice due to the following reasons:
- Boost Software License is very similar to the MIT license except that the Boost Software License has license and copyright notice for source, not just only license and copyright notice. I do not this additional condition is necessary for our package. The MIT license is more familiar to most people, which makes life easier for users.

- The MIT license has fewer restrictions compared with GNU GPLv3 and Apache. The only restriction an MIT license places on is keeping the license and copyright notice when repurposing, redistributing, or reusing. Given that the nature of this package is a university project, a permissive and open-ended license seems the most reasonable choice. 

However, there may be some drawback if we use the MIT license:
- If we want to put more restrictions on the future, the process will be very difficult.
- It does not explicitly cover patent grants.

Overall, I think base on the nature and main purpose of our package, sticking with MIT license would be a reasonable choice.

**Comment by elabandari** [comment]
Hi @JuntingHe,

Thank you so much for kick-starting this discussion and so beautifully summarizing these different options for us. I agree that the MIT License is the best option given its permissiveness and protection from liabilities.

Best, 
Ela

**Comment by elina-linglin** [comment]
Hi @JuntingHe,

Thank you for the detailed information about each option. I think that the MIT License looks the most appropriate for our project. 

Best,
Elina

**Comment by athy9193** [comment]
Hi @JuntingHe! I agree with your assessment.  I think MIT License would suit our package best.

**Comment by JuntingHe** [comment]
After discussion, our team decided to stick with our original MIT license because it is permissive and familiar to most people. Also, it fits the nature of our package.
